language: node_js

node_js:
  - '12'
  - '10'

before_install:
  - node ./build/update-dependencies.js

script:
  - jest --coverage --coverageReporters text lcovonly

after_success:
  - cat ./coverage/lcov.info | coveralls
